"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

interface Translations {
  [key: string]: string | Translations
}

const translations: Record<string, Translations> = {
  en: {
    nav: {
      countries: "Countries",
      search: "Search",
      chat: "Chat",
      premium: "Premium",
      profile: "Profile",
      about: "About",
      backToHome: "Back to Home",
    },
    auth: {
      login: "Login",
      signIn: "Sign In",
      signUp: "Sign Up",
      signup: "Sign Up",
      email: "Email",
      password: "Password",
      fullName: "Full Name",
      confirmPassword: "Confirm Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      continueWithGoogle: "Continue with Google",
      continueWithFacebook: "Continue with Facebook",
      continueWithLinkedIn: "Continue with LinkedIn",
      continueAsGuest: "Continue as Guest",
      orContinueWith: "or continue with email",
      orSignUpWith: "or sign up with email",
      emailPlaceholder: "Enter your email",
      passwordPlaceholder: "Enter your password",
      namePlaceholder: "Enter your full name",
      createPassword: "Create a password",
      confirmPasswordPlaceholder: "Confirm your password",
      agreeToTerms: "I agree to the",
      termsOfService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      noAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      createAccount: "Create Account",
      signingIn: "Signing in...",
      creatingAccount: "Creating account...",
      welcomeBack: "Welcome back!",
      loginSuccess: "You have been successfully logged in.",
      accountCreated: "Account created!",
      signupSuccess: "Welcome to GlobeGuru. Please check your email to verify your account.",
      socialLogin: "Social Login",
      socialSignup: "Social Sign Up",
      redirecting: "Redirecting to",
      tagline: "Your trusted travel law companion",
      signInSubtitle: "Welcome back to your legal travel guide",
      signupSubtitle: "Join thousands of informed travelers",
      trustedBy: "Trusted by travelers worldwide",
      secureData: "Your data is secure and encrypted",
      error: "Error",
      passwordMismatch: "Passwords do not match",
      signUpWithGoogle: "Sign up with Google",
      signUpWithFacebook: "Sign up with Facebook",
      signUpWithLinkedIn: "Sign up with LinkedIn",
    },
    home: {
      lawOfDay: "Law of the Day",
      searchPlaceholder: "Search laws by country or topic...",
      searchButton: "Search",
      featuredCountries: "Featured Countries",
      viewAll: "View All Countries",
      allCountries: "All Countries",
      showingResults: "Showing {count} countries",
      filterByRegion: "Filter by Region",
      filterByRisk: "Filter by Risk Level",
      sortBy: "Sort by",
      alphabetical: "Alphabetical",
      riskLevel: "Risk Level",
      lawCount: "Law Count",
    },
    features: {
      offline: "Offline Access",
      offlineDesc: "Access laws even without internet",
      multilingual: "Multilingual",
      multilingualDesc: "Available in multiple languages",
      updated: "Always Updated",
      updatedDesc: "Latest legal information",
      expert: "Expert Verified",
      expertDesc: "Reviewed by legal professionals",
    },
    chat: {
      title: "Legal Assistant",
      placeholder: "Ask about laws in any country...",
      send: "Send",
      quickQuestions: "Quick Questions",
      askCountry: "Ask about a specific country",
      searchTopic: "Search by legal topic",
      safetyTips: "Get travel safety tips",
      emergency: "Emergency procedures",
      typing: "AI is typing...",
    },
    premium: {
      title: "Upgrade to Premium",
      subtitle: "Unlock all features for the complete travel experience",
      current: "Current Plan: Free",
      upgrade: "Upgrade Now",
    },
    search: {
      title: "Advanced Search",
      subtitle: "Find specific laws and regulations with detailed filters",
      placeholder: "Search laws, regulations, or topics...",
      filters: "Filters",
      country: "Country",
      category: "Category",
      riskLevel: "Risk Level",
      selectCountry: "Select country",
      selectCategory: "Select category",
      selectRisk: "Select risk level",
      results: "Search Results",
      sortRelevance: "Sort by Relevance",
      sortCountry: "Sort by Country",
      sortRisk: "Sort by Risk Level",
      sortCategory: "Sort by Category",
      readMore: "Read More",
      noResults: "No results found",
      tryDifferent: "Try different search terms or filters",
    },
    location: {
      detected: "Location Detected",
      detectedIn: "We detected you're in",
      yourLocation: "Your Location",
      suggestion: "Would you like to explore the laws for your current location?",
      viewLaws: "View Laws",
      later: "Later",
    },
    theme: {
      toggle: "Toggle theme",
      light: "Light",
      dark: "Dark",
    },
    countries: {
      overview: "Overview",
      categories: "Categories",
      keyLaws: "Key Laws",
      emergency: "Emergency",
      riskComplexity: "Legal Complexity",
      travelerStats: "Traveler Stats",
      lastUpdated: "Last Updated",
      saveOffline: "Save Offline",
      share: "Share",
      addFavorites: "Add to Favorites",
      mostSearched: "Most Searched",
      commonIssues: "Common Issues",
      successRate: "Success Rate",
      content: "Content",
      verification: "Verification",
      expertVerified: "Expert Verified",
      viewLaws: "View {count} Laws",
      summary: "Summary",
      details: "Details",
      penalties: "Penalties",
      travelTips: "Travel Tips",
      emergencyContacts: "Emergency Contacts",
      police: "Police Emergency",
      embassy: "Embassy",
      touristHotline: "Tourist Hotline",
    },
    profile: {
      personalInfo: "Personal Information",
      homeCountry: "Home Country",
      preferredLanguage: "Preferred Language",
      saveChanges: "Save Changes",
      offlineAccess: "Offline Access",
      selectedCountry: "Selected Country for Offline Access",
      downloadLaws: "Download {country} Laws",
      favoriteCountries: "Favorite Countries",
      recentSearches: "Recent Searches",
      searchAgain: "Search Again",
      notifications: "Notification Preferences",
      pushNotifications: "Push Notifications",
      importantUpdates: "Receive important legal updates",
      travelAlerts: "Travel Alerts",
      alertsDescription: "Get notified about law changes in your favorite countries",
      newsletter: "Newsletter",
      weeklyDigest: "Weekly digest of travel law updates",
      appPreferences: "App Preferences",
      defaultRegion: "Default Search Region",
      riskDisplay: "Risk Level Display",
      showAllLevels: "Show All Levels",
      mediumHighOnly: "Medium & High Only",
      highOnly: "High Risk Only",
      countriesExplored: "Countries Explored",
      lawsRead: "Laws Read",
      daysActive: "Days Active",
      totalLawsViewed: "total laws viewed",
      sinceJoining: "since joining",
      recentActivity: "Recent Activity",
      viewed: "Viewed",
      saved: "Saved",
      downloaded: "Downloaded",
      searched: "Searched",
    },
    about: {
      mission: "Our Mission",
      meetTeam: "Meet Our Team",
      getInTouch: "Get In Touch",
      generalInquiries: "General Inquiries",
      legalTeam: "Legal Team",
      support: "Support",
      founder: "Founder & CEO",
      legalDirector: "Legal Director",
      headOfContent: "Head of Content",
      accuracyTrust: "Accuracy & Trust",
      communityFirst: "Community First",
      globalAccessibility: "Global Accessibility",
      innovation: "Innovation",
    },
    pwa: {
      install: "Install GlobeGuru",
      accessOffline: "Access offline anywhere",
      installApp: "Install App",
      later: "Later",
    },
    offline: {
      manager: "Offline Access Manager",
      online: "Online",
      offline: "Offline",
      usingOfflineData: "Using Offline Data",
      downloaded: "Downloaded",
      downloading: "Downloading...",
      download: "Download",
      update: "Update",
      remove: "Remove",
      size: "Size",
      downloadedOn: "Downloaded",
      complete: "complete",
      freePlan: "Free plan: 1 country offline • Premium: Unlimited countries",
      upgradePremium: "Upgrade to Premium",
      downloadComplete: "Download Complete",
      availableOffline: "laws are now available offline",
      dataRemoved: "Offline Data Removed",
      removedFromStorage: "Country data has been removed from offline storage",
      updating: "Updating...",
      checkingUpdates: "Checking for latest legal updates",
    },
  },
  fr: {
    nav: {
      countries: "Pays",
      search: "Rechercher",
      chat: "Chat",
      premium: "Premium",
      profile: "Profil",
      about: "À propos",
      backToHome: "Retour à l'accueil",
    },
    auth: {
      login: "Connexion",
      signIn: "Se connecter",
      signUp: "S'inscrire",
      signup: "S'inscrire",
      email: "Email",
      password: "Mot de passe",
      fullName: "Nom complet",
      confirmPassword: "Confirmer le mot de passe",
      rememberMe: "Se souvenir de moi",
      forgotPassword: "Mot de passe oublié ?",
      continueWithGoogle: "Continuer avec Google",
      continueWithFacebook: "Continuer avec Facebook",
      continueWithLinkedIn: "Continuer avec LinkedIn",
      continueAsGuest: "Continuer en tant qu'invité",
      orContinueWith: "ou continuer avec email",
      orSignUpWith: "ou s'inscrire avec email",
      emailPlaceholder: "Entrez votre email",
      passwordPlaceholder: "Entrez votre mot de passe",
      namePlaceholder: "Entrez votre nom complet",
      createPassword: "Créer un mot de passe",
      confirmPasswordPlaceholder: "Confirmez votre mot de passe",
      agreeToTerms: "J'accepte les",
      termsOfService: "Conditions d'utilisation",
      and: "et",
      privacyPolicy: "Politique de confidentialité",
      noAccount: "Vous n'avez pas de compte ?",
      alreadyHaveAccount: "Vous avez déjà un compte ?",
      createAccount: "Créer un compte",
      signingIn: "Connexion en cours...",
      creatingAccount: "Création du compte...",
      welcomeBack: "Bon retour !",
      loginSuccess: "Vous avez été connecté avec succès.",
      accountCreated: "Compte créé !",
      signupSuccess: "Bienvenue sur GlobeGuru. Veuillez vérifier votre email pour confirmer votre compte.",
      socialLogin: "Connexion sociale",
      socialSignup: "Inscription sociale",
      redirecting: "Redirection vers",
      tagline: "Votre compagnon de voyage juridique de confiance",
      signInSubtitle: "Bon retour sur votre guide juridique de voyage",
      signupSubtitle: "Rejoignez des milliers de voyageurs informés",
      trustedBy: "Fait confiance par les voyageurs du monde entier",
      secureData: "Vos données sont sécurisées et cryptées",
      error: "Erreur",
      passwordMismatch: "Les mots de passe ne correspondent pas",
      signUpWithGoogle: "S'inscrire avec Google",
      signUpWithFacebook: "S'inscrire avec Facebook",
      signUpWithLinkedIn: "S'inscrire avec LinkedIn",
    },
    home: {
      lawOfDay: "Loi du Jour",
      searchPlaceholder: "Rechercher des lois par pays ou sujet...",
      searchButton: "Rechercher",
      featuredCountries: "Pays en Vedette",
      viewAll: "Voir Tous les Pays",
      allCountries: "Tous les Pays",
      showingResults: "Affichage de {count} pays",
      filterByRegion: "Filtrer par Région",
      filterByRisk: "Filtrer par Niveau de Risque",
      sortBy: "Trier par",
      alphabetical: "Alphabétique",
      riskLevel: "Niveau de Risque",
      lawCount: "Nombre de Lois",
    },
    features: {
      offline: "Accès Hors Ligne",
      offlineDesc: "Accédez aux lois même sans internet",
      multilingual: "Multilingue",
      multilingualDesc: "Disponible en plusieurs langues",
      updated: "Toujours à Jour",
      updatedDesc: "Informations juridiques récentes",
      expert: "Vérifié par des Experts",
      expertDesc: "Révisé par des professionnels du droit",
    },
    chat: {
      title: "Assistant Juridique",
      placeholder: "Posez des questions sur les lois de n'importe quel pays...",
      send: "Envoyer",
      quickQuestions: "Questions Rapides",
      askCountry: "Demander à propos d'un pays spécifique",
      searchTopic: "Rechercher par sujet juridique",
      safetyTips: "Obtenir des conseils de sécurité de voyage",
      emergency: "Procédures d'urgence",
      typing: "L'IA tape...",
    },
    premium: {
      title: "Passer à Premium",
      subtitle: "Débloquez toutes les fonctionnalités pour une expérience de voyage complète",
      current: "Plan Actuel: Gratuit",
      upgrade: "Mettre à Niveau",
    },
    search: {
      title: "Recherche Avancée",
      subtitle: "Trouvez des lois et réglementations spécifiques avec des filtres détaillés",
      placeholder: "Rechercher des lois, réglementations ou sujets...",
      filters: "Filtres",
      country: "Pays",
      category: "Catégorie",
      riskLevel: "Niveau de Risque",
      selectCountry: "Sélectionner un pays",
      selectCategory: "Sélectionner une catégorie",
      selectRisk: "Sélectionner un niveau de risque",
      results: "Résultats de Recherche",
      sortRelevance: "Trier par Pertinence",
      sortCountry: "Trier par Pays",
      sortRisk: "Trier par Niveau de Risque",
      sortCategory: "Trier par Catégorie",
      readMore: "Lire Plus",
      noResults: "Aucun résultat trouvé",
      tryDifferent: "Essayez des termes de recherche ou filtres différents",
    },
    location: {
      detected: "Localisation Détectée",
      detectedIn: "Nous avons détecté que vous êtes en",
      yourLocation: "Votre Localisation",
      suggestion: "Souhaitez-vous explorer les lois de votre localisation actuelle ?",
      viewLaws: "Voir les Lois",
      later: "Plus tard",
    },
    theme: {
      toggle: "Basculer le thème",
      light: "Clair",
      dark: "Sombre",
    },
    countries: {
      overview: "Aperçu",
      categories: "Catégories",
      keyLaws: "Lois Clés",
      emergency: "Urgence",
      riskComplexity: "Complexité Juridique",
      travelerStats: "Statistiques Voyageurs",
      lastUpdated: "Dernière Mise à Jour",
      saveOffline: "Sauvegarder Hors Ligne",
      share: "Partager",
      addFavorites: "Ajouter aux Favoris",
      mostSearched: "Plus Recherché",
      commonIssues: "Problèmes Courants",
      successRate: "Taux de Réussite",
      content: "Contenu",
      verification: "Vérification",
      expertVerified: "Vérifié par des Experts",
      viewLaws: "Voir {count} Lois",
      summary: "Résumé",
      details: "Détails",
      penalties: "Pénalités",
      travelTips: "Conseils de Voyage",
      emergencyContacts: "Contacts d'Urgence",
      police: "Urgence Police",
      embassy: "Ambassade",
      touristHotline: "Ligne d'Assistance Touristique",
    },
    profile: {
      personalInfo: "Informations Personnelles",
      homeCountry: "Pays d'Origine",
      preferredLanguage: "Langue Préférée",
      saveChanges: "Sauvegarder les Modifications",
      offlineAccess: "Accès Hors Ligne",
      selectedCountry: "Pays Sélectionné pour l'Accès Hors Ligne",
      downloadLaws: "Télécharger les Lois de {country}",
      favoriteCountries: "Pays Favoris",
      recentSearches: "Recherches Récentes",
      searchAgain: "Rechercher à Nouveau",
      notifications: "Préférences de Notification",
      pushNotifications: "Notifications Push",
      importantUpdates: "Recevoir des mises à jour juridiques importantes",
      travelAlerts: "Alertes de Voyage",
      alertsDescription: "Être notifié des changements de lois dans vos pays favoris",
      newsletter: "Newsletter",
      weeklyDigest: "Digest hebdomadaire des mises à jour juridiques de voyage",
      appPreferences: "Préférences de l'Application",
      defaultRegion: "Région de Recherche par Défaut",
      riskDisplay: "Affichage du Niveau de Risque",
      showAllLevels: "Afficher Tous les Niveaux",
      mediumHighOnly: "Moyen et Élevé Seulement",
      highOnly: "Risque Élevé Seulement",
      countriesExplored: "Pays Explorés",
      lawsRead: "Lois Lues",
      daysActive: "Jours Actifs",
      totalLawsViewed: "total des lois consultées",
      sinceJoining: "depuis l'inscription",
      recentActivity: "Activité Récente",
      viewed: "Consulté",
      saved: "Sauvegardé",
      downloaded: "Téléchargé",
      searched: "Recherché",
    },
    about: {
      mission: "Notre Mission",
      meetTeam: "Rencontrez Notre Équipe",
      getInTouch: "Nous Contacter",
      generalInquiries: "Demandes Générales",
      legalTeam: "Équipe Juridique",
      support: "Support",
      founder: "Fondateur et PDG",
      legalDirector: "Directeur Juridique",
      headOfContent: "Responsable du Contenu",
      accuracyTrust: "Précision et Confiance",
      communityFirst: "Communauté d'Abord",
      globalAccessibility: "Accessibilité Mondiale",
      innovation: "Innovation",
    },
    pwa: {
      install: "Installer GlobeGuru",
      accessOffline: "Accès hors ligne partout",
      installApp: "Installer l'App",
      later: "Plus tard",
    },
    offline: {
      manager: "Gestionnaire d'Accès Hors Ligne",
      online: "En ligne",
      offline: "Hors ligne",
      usingOfflineData: "Utilisation des données hors ligne",
      downloaded: "Téléchargé",
      downloading: "Téléchargement...",
      download: "Télécharger",
      update: "Mettre à jour",
      remove: "Supprimer",
      size: "Taille",
      downloadedOn: "Téléchargé le",
      complete: "terminé",
      freePlan: "Plan gratuit : 1 pays hors ligne • Premium : Pays illimités",
      upgradePremium: "Passer à Premium",
      downloadComplete: "Téléchargement Terminé",
      availableOffline: "lois sont maintenant disponibles hors ligne",
      dataRemoved: "Données Hors Ligne Supprimées",
      removedFromStorage: "Les données du pays ont été supprimées du stockage hors ligne",
      updating: "Mise à jour...",
      checkingUpdates: "Vérification des dernières mises à jour juridiques",
    },
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("globeguru-language")
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fr")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang)
    localStorage.setItem("globeguru-language", lang)
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    let result = typeof value === "string" ? value : key

    // Replace parameters in the string
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        result = result.replace(`{${paramKey}}`, String(paramValue))
      })
    }

    return result
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
